
security:
    providers:
        in_memory:
            memory:
                user:
                    name: user
                    password: userpass
                    roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            http_basic: ~
        main:
            anonymous: ~

    access_control:
            - { path: ^/product, roles: ROLE_USER }
